# Generated by Django 5.2.1 on 2025-05-21 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitutorapp', '0001_initial'),
        ('coursesapp', '0006_module_content_quiz_passing_score_quizquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled_for_students', models.BooleanField(default=True, help_text='Enable AI tutor for enrolled students')),
                ('is_enabled_for_instructors', models.BooleanField(default=True, help_text='Enable AI tutor for course instructors')),
                ('system_prompt', models.TextField(blank=True, help_text='Custom system prompt to guide the AI tutor behavior')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='coursesapp.course')),
            ],
            options={
                'verbose_name': 'Course AI Settings',
                'verbose_name_plural': 'Course AI Settings',
            },
        ),
    ]
